### ISSUE TITLE
Keep state at URL

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-rich#5]
Using [vue router](https://github.com/vuejs/vue-router-next) history the URL should reflect state of field `ppn` and `dbkey` so we can deep-link to examples.

**Comment by stefandesu** [comment]
Questions @nichtich: 

1. Should the records automatically loaded if they are given via URL parameters?
2. If the answer to 1 is yes, does it also apply if it's the default PPN?

Currently, whenever the record is loaded (via "Laden" or choosing one of the example PPNs), the URL is adjusted, and if the site is loaded with the PPN given, it will be loaded automatically.

**Comment by nichtich** [comment]
Yes to 1 and remove the Default PPN/recordText
